### ISSUE TITLE
unmatched open brace in list

### ISSUE THREAD

**Issue by torstenberg** [mittelmark/DGTcl#3]
When testing this new addition, I get the following error using the filter version (not the standalone tapp):

```
pandoc threshold-analysis.tmd -f markdown -t markdown -o test.md --filter /Users/Torsten/Tcl/apps/pandoc-tcl-filter/pandoc-tcl-filter.tcl 
unmatched open brace in list
    while executing
"llength $res"
    (procedure "main" line 78)
    invoked from within
"main $jsonData"
    invoked from within
"puts -nonewline [main $jsonData]"
    (file "/Users/Torsten/Tcl/apps/pandoc-tcl-filter/pandoc-tcl-filter.tcl" line 675)
Error running filter /Users/Torsten/Tcl/apps/pandoc-tcl-filter/pandoc-tcl-filter.tcl:
Filter returned error status 1
```

The 'tmd' file is my markdown file with Tcl code blocks. It seems that the `$res` in line 616 of pandoc-tcl-filter.tcl is not a clean Tcl list. 

I wish I could extract the Tcl code blocks into a Tcl file from the original 'tmd' file to test that it is not a problem with my code. But, could this be something in the filter code?

**Comment by mittelmark** [comment]
I uploaded a version which allows to tangle the source code.
You can use it like this:
tclsh pandoc-tcl-filter.tcl yourfile.tmd --tangle .tcl 

Which should print the Tcl code to the terminal. I would like to see how the list looks like, does the code should be just a string of Markdown table code.

**Comment by mittelmark** [comment]
I added my list2table code examples which are working quite nice in the tests/table.html example, see here:
https://htmlpreview.github.io/?https://github.com/mittelmark/DGTcl/blob/master/pandoc-tcl-filter/tests/table.html

So to debug your example, I would need a minimal example code section which reproduces this error.

**Comment by torstenberg** [comment]
OK, now I got a minimal example. That was not easy ... but try this file:

[test.md](https://github.com/mittelmark/DGTcl/files/7697838/test.md)

and run it with the following command:

```
pandoc test.md -f markdown -t markdown -o test_out.md --filter pandoc-tcl-filter.tcl
```

That will produce the error. It doesn't matter that the Tcl script itself produces an error here because the command `db` is not defined.

If you remove the 'results' part from the list of code attributes to look like this: `{.tcl echo=false}` then the filter will run fine.

As for the `--tangle` option, this is great, thanks! I just noted that it will not work when there is a space between the last backtick and the opening brace of the code attributes, as is the case in my test file. This is allowed in Pandoc's markdown. I have done some trial and error with Lua (not knowing the language and Pandoc'S interface to Lua more than to do very basic things) but I came up with a Lua filter to extract all code blocks from a markdown file and write them to the output file. I put the code on the Wiki [here](https://wiki.tcl-lang.org/page/pandoc).

**Comment by mittelmark** [comment]
Ok, I fixed this small tangle issue. results="asis" means that you return in the last code statement a string in Markdown format not a Tcl data structure like a list. In case of LaTeX you have to return LaTeX code etc. So my guess is that you have to convert your list to a Markdown table for instance formulated as a string. Look at my example here (list2table):

https://htmlpreview.github.io/?https://github.com/mittelmark/DGTcl/blob/master/pandoc-tcl-filter/tests/table.html

However I will anyway try to catch this error by creating my own list, as I do not have the database.

Embedding the sqlite3 command line application directly as well would be also interesting. sqlite3 now has mode .markdown, so that could be as easy as:

```{.sqlite file="sample.sqlite3"}
select * from test limit 5;
```

and you get the sqlite3 table.

**Comment by mittelmark** [comment]
Update code was:

` ` ` {.sqlite file="test.sqlite" mode="markdown"}
select * test limit 5
` ` `

**Comment by mittelmark** [comment]
I found the problem, it was a variable name clash, used res for the pandoc return and for the filter return. Now it should be fixed. On the fly added as well the sqlite filter for sqlite3 terminal application, see here:

http://htmlpreview.github.io/?https://github.com/mittelmark/DGTcl/blob/master/pandoc-tcl-filter/filter/filter-sqlite.html

**Comment by torstenberg** [comment]
Great! Letting sqlite output markdown is quite handy, actually!

However, I still have a problem. Consider this markdown file:

[test2.md](https://github.com/mittelmark/DGTcl/files/7707280/test2.md)

Running it through Pandoc like this:

```
pandoc test.md  -f markdown -t markdown -o test_out.md --filter ~/Tcl/apps/pandoc-tcl-filter/pandoc-tcl-filter.tcl
```

results in the following error:

```
Error running filter /Users/Torsten/Tcl/apps/pandoc-tcl-filter/pandoc-tcl-filter.tcl:
Error in $.blocks[1]: key "t" not found
```

It doesn't matter whether the line is `puts` or `return`. Did I misunderstand when you wrote "asis" needs to return markdown? Anyhow, it shouldn't perhaps throw this error in any case.

**Comment by mittelmark** [comment]
results="asis" should return Markdown for a Markdown document, tex-code for a LaTeX document asciidoc for a asciidoc document and so on.

Yes this puts statements should anyway not throw an error as it is a valid Tcl command. The puts proc is renamed and replaced by a modified version in the code to catch its output and bring it after the code block. The filter mechanism works only on the Json Tree on stdout, so puts calls needs to be catched. This catch is indeed not tested for all bells and whistles. That return as well throws an error is however indeed problematic as this is valid Markdown. I will look into this.

**Comment by mittelmark** [comment]
Hmm, I do not get this error:
Could you try this standalone file 

https://github.com/mittelmark/DGTcl/suites/4648174922/artifacts/126121328 

which comes will all the filters, all the libaries and rl_json builds for Mac, Win, and Linux. 

There is a file tests/asis.md

Which I can convert like this:

 ./pandoc-tcl-filter.tapp tests/asis.md asis.md -s

May be it is an rl_json or pandoc issue. What version of pandoc you have?

**Comment by mittelmark** [comment]
Here the sample file: https://github.com/mittelmark/DGTcl/blob/master/pandoc-tcl-filter/tests/asis.md

**Comment by torstenberg** [comment]
OK, I get this:

```
~/Downloads/pandoc-tcl-filter % ./pandoc-tcl-filter.tapp asis.md asis_out.md -s
Error running filter ./pandoc-tcl-filter.tapp:
Error in $.blocks[5]: key "t" not found
    while executing
"exec pandoc [lindex $argv 0] --filter $argv0 -o {*}[lrange $argv 1 end]"
    invoked from within
"if {[llength $argv] > 1 && [file exists [lindex $argv 0]]} {
    if {[auto_execok pandoc] eq ""} {
        puts "Error: Document conversion needs pand..."
    (file "./pandoc-tcl-filter.tapp" line 508)
~/Downloads/pandoc-tcl-filter % 
```

My Pandoc version is current:

```
~/Downloads/pandoc-tcl-filter % pandoc -v
pandoc 2.16.2
Compiled with pandoc-types 1.22.1, texmath 0.12.3.3, skylighting 0.12.1,
citeproc 0.6, ipynb 0.1.0.2
User data directory: /Users/Torsten/.local/share/pandoc
Copyright (C) 2006-2021 John MacFarlane. Web:  https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

And rl_json is:

```
~/Downloads/pandoc-tcl-filter % tclsh
% package require rl_json   
0.11.0
```

**Comment by mittelmark** [comment]
Thanks, it is the pandoc version. I have 2.9 from 2020 where it works, checked with 2.12 from here https://github.com/jgm/pandoc/releases/ and I get the same error like you. Will look into this.

**Comment by mittelmark** [comment]
I think I fixed it. Between pandoc version 2.9 and 2.12 they changed the order of json output 2.9 block then meta, 2.12++ meta than block. As I just do a dummy regsub replace of the json code this failed for newer version. I pushed the changed code to github and did as well a new standalone build: 

https://github.com/mittelmark/DGTcl/suites/4663524527/artifacts/126753051

Hope this works now. See here my output with pandoc 2.14

http://htmlpreview.github.io/?https://github.com/mittelmark/DGTcl/blob/master/pandoc-tcl-filter/pandoc-tcl-filter.html

I added as well a few more PlantUML examples: 

http://htmlpreview.github.io/?https://github.com/mittelmark/DGTcl/blob/master/pandoc-tcl-filter/filter/filter-puml.html

**Comment by torstenberg** [comment]
Great! I can confirm this works now. Thanks for your help and this wonderful package!
